### PR TITLE
Added dismiss method to dismiss modally presented view controllers

### PR DESCRIPTION
**Pull request by alanzeino**

### CODE REVIEW

**Comment by kastiglione** [comment]
@alanzeino Did you say the CLA form shows you've already signed it? https://code.facebook.com/cla

**Comment by jamesgpearce** [comment]
The CLA is good now. Go for it.

**Comment by alanzeino** [comment]
Thinking of removing the requirement for the view controller to have a nav controller, since that isn't a requirement for a view controller to be dismissed.

**Comment by kastiglione** [comment]
@alanzeino Are you still planning to make changes?

**Comment by kastiglione** [comment]
@alanzeino

**Comment by alanzeino** [comment]
Yep, lemme update this to make it more robust.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Pull request closed without merging**
