### PR TITLE
add swift support by explicitly specifying language in LLDB commands

### PR DESCRIPTION
**Pull request by moreindirection**

### CODE REVIEW

**Comment by moreindirection** [comment]
Do I really have to sign the CLA for such a trivial change as adding arguments to LLDB commands?

**Comment by kastiglione** [comment]
I've asked before about trivial changes, but unfortunately was told signing is still a requirement. The good news is that the license takes seconds to submit if you're not worried about what it says :) But seriously, it's short and straight forward. I found it very easy to scan through.

Either way, I appreciate you taking the time to give the valuable feedback, and the time to open the pull request. Thank you!

**Comment by kastiglione** [comment]
Hi @moreindirection, did you decide against signing the CLA?

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kastiglione** [comment]
@moreindirection Please feel free to reopen anytime.

**Pull request closed without merging**
